name: Node.js CI

on:
  push:
    branches: [ "main", "dev", "client" ]
  pull_request:
    branches: [ "main", "dev", "client"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.X, 22.X]  

    steps:
    - uses: actions/checkout@v4
    
    - name: Verify file structure
      run: |
        echo "Checking project structure..."
        ls -la client/src/lib/ || echo "lib directory might be missing"
        find client/src -name "utils*" -type f 2>/dev/null || echo "No utils file found"
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      working-directory: client
    
    - name: Build
      run: npm run build
      working-directory: client
    
    - name: Test
      run: npm test
      working-directory: client
