name: Test Reports

on:
  push:
    branches: [ main, develop, testing ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Install dependencies
      run: |
        cd client
        npm ci
    
    - name: Run tests with reports
      run: |
        cd client
        npm run test:ci
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          client/testing/reports/
          client/testing/coverage/
        retention-days: 30
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Vitest Tests
        path: client/testing/reports/junit.xml
        reporter: java-junit
        fail-on-error: true
    
    - name: Comment Coverage Report
      uses: 5monkeys/cobertura-action@master
      if: github.event_name == 'pull_request'
      with:
        path: client/testing/coverage/cobertura-coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 70
        fail_below_threshold: false
        show_missing: true
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: client/testing/coverage/lcov.info
        flags: frontend
        name: frontend-coverage
        fail_ci_if_error: false